
# This file is automatically generated, you probably don't want to edit this

hatvaluesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "hatvaluesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dv = NULL,
            iv = NULL, ...) {

            super$initialize(
                package="jmvtest",
                name="hatvalues",
                requiresData=TRUE,
                ...)

            private$..dv <- jmvcore::OptionVariable$new(
                "dv",
                dv)
            private$..iv <- jmvcore::OptionVariables$new(
                "iv",
                iv)

            self$.addOption(private$..dv)
            self$.addOption(private$..iv)
        }),
    active = list(
        dv = function() private$..dv$value,
        iv = function() private$..iv$value),
    private = list(
        ..dv = NA,
        ..iv = NA)
)

hatvaluesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "hatvaluesResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        coeftable = function() private$.items[["coeftable"]],
        hv = function() private$.items[["hv"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Save hatvalues")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Save hatvalues"))
            self$add(jmvcore::Table$new(
                options=options,
                name="coeftable",
                title="Regression Coefficients",
                rows=1,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="coef", 
                        `title`="B", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="S.E.", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="pvalue"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="hv",
                title="Leverage",
                varTitle="Leverage",
                varDescription="Leverage",
                measureType="continuous",
                clearWith=list(
                    "dv",
                    "iv")))}))

hatvaluesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "hatvaluesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvtest",
                name = "hatvalues",
                version = c(1,0,0),
                options = options,
                results = hatvaluesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Save hatvalues
#'
#' 
#' @param data .
#' @param dv .
#' @param iv .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$coeftable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$hv} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$coeftable$asDF}
#'
#' \code{as.data.frame(results$coeftable)}
#'
#' @export
hatvalues <- function(
    data,
    dv,
    iv) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("hatvalues requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dv)) dv <- jmvcore::resolveQuo(jmvcore::enquo(dv))
    if ( ! missing(iv)) iv <- jmvcore::resolveQuo(jmvcore::enquo(iv))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dv), dv, NULL),
            `if`( ! missing(iv), iv, NULL))


    options <- hatvaluesOptions$new(
        dv = dv,
        iv = iv)

    analysis <- hatvaluesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

